// This file will import from Orval-generated API after running: npm run generate:api
// For now, these are placeholder imports that will work once the API is generated
import { apiClient } from '@/lib/api-client';

// Types - these will be generated by Orval
export interface CreateReviewRequest {
  bookingId: string;
  rating: number;
  comment?: string;
}

export interface ReviewResponse {
  id: string;
  rating: number;
  comment?: string;
  createdAt: string;
  user: {
    name: string;
    avatarUrl?: string;
  };
  route: {
    originCity: string;
    destinationCity: string;
  };
  tripDate: string;
}

export interface PagedReviewResponse {
  content: ReviewResponse[];
  page?: {
    number: number;
    size: number;
    totalElements: number;
    totalPages: number;
  };
}

// API functions - these will be replaced with Orval-generated functions
// After Orval generation, import from: '@/features/api/reviews/reviews'
export const createReview = async (request: CreateReviewRequest): Promise<ReviewResponse> => {
  const response = await apiClient.post<{ data: ReviewResponse }>('/api/reviews', request);
  return response.data.data;
};

export const getReviewsByOperator = async (
  operatorId: string,
  page = 0,
  size = 10,
): Promise<PagedReviewResponse> => {
  const response = await apiClient.get<{ data: PagedReviewResponse }>(
    `/api/reviews/operator/${operatorId}?page=${page}&size=${size}`,
  );
  return response.data.data;
};

export const getReviewByBookingId = async (bookingId: string): Promise<ReviewResponse | null> => {
  try {
    const response = await apiClient.get<{ data: ReviewResponse }>(
      `/api/reviews/booking/${bookingId}`,
    );
    return response.data.data;
  } catch (error: unknown) {
    // Handle 404 as "no review exists" (not an error)
    if (
      error &&
      typeof error === 'object' &&
      'response' in error &&
      error.response &&
      typeof error.response === 'object' &&
      'status' in error.response &&
      error.response.status === 404
    ) {
      return null;
    }
    // For other errors, rethrow or return null
    console.error('Error fetching review:', error);
    return null;
  }
};
