/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Bus,
  CreateBusRequest,
  DeleteBusParams,
  GetAllBusesParams,
  PagedModelBus
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const updateBus = (
    id: string,
    createBusRequest: CreateBusRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Bus>(
      {url: `/api/buses/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createBusRequest
    },
      options);
    }
  


export const getUpdateBusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBus>>, TError,{id: string;data: CreateBusRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateBus>>, TError,{id: string;data: CreateBusRequest}, TContext> => {

const mutationKey = ['updateBus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBus>>, {id: string;data: CreateBusRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateBus(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateBusMutationResult = NonNullable<Awaited<ReturnType<typeof updateBus>>>
    export type UpdateBusMutationBody = CreateBusRequest
    export type UpdateBusMutationError = unknown

    export const useUpdateBus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBus>>, TError,{id: string;data: CreateBusRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateBus>>,
        TError,
        {id: string;data: CreateBusRequest},
        TContext
      > => {

      const mutationOptions = getUpdateBusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteBus = (
    id: string,
    params?: DeleteBusParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/buses/${id}`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteBusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBus>>, TError,{id: string;params?: DeleteBusParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBus>>, TError,{id: string;params?: DeleteBusParams}, TContext> => {

const mutationKey = ['deleteBus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBus>>, {id: string;params?: DeleteBusParams}> = (props) => {
          const {id,params} = props ?? {};

          return  deleteBus(id,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBusMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBus>>>
    
    export type DeleteBusMutationError = unknown

    export const useDeleteBus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBus>>, TError,{id: string;params?: DeleteBusParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBus>>,
        TError,
        {id: string;params?: DeleteBusParams},
        TContext
      > => {

      const mutationOptions = getDeleteBusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllBuses = (
    params: GetAllBusesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PagedModelBus>(
      {url: `/api/buses`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllBusesQueryKey = (params?: GetAllBusesParams,) => {
    return [
    `/api/buses`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllBusesQueryOptions = <TData = Awaited<ReturnType<typeof getAllBuses>>, TError = unknown>(params: GetAllBusesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBuses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllBusesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBuses>>> = ({ signal }) => getAllBuses(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllBuses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllBusesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllBuses>>>
export type GetAllBusesQueryError = unknown


export function useGetAllBuses<TData = Awaited<ReturnType<typeof getAllBuses>>, TError = unknown>(
 params: GetAllBusesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBuses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBuses>>,
          TError,
          Awaited<ReturnType<typeof getAllBuses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBuses<TData = Awaited<ReturnType<typeof getAllBuses>>, TError = unknown>(
 params: GetAllBusesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBuses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBuses>>,
          TError,
          Awaited<ReturnType<typeof getAllBuses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBuses<TData = Awaited<ReturnType<typeof getAllBuses>>, TError = unknown>(
 params: GetAllBusesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBuses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllBuses<TData = Awaited<ReturnType<typeof getAllBuses>>, TError = unknown>(
 params: GetAllBusesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBuses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllBusesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createBus = (
    createBusRequest: CreateBusRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Bus>(
      {url: `/api/buses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createBusRequest, signal
    },
      options);
    }
  


export const getCreateBusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBus>>, TError,{data: CreateBusRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createBus>>, TError,{data: CreateBusRequest}, TContext> => {

const mutationKey = ['createBus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBus>>, {data: CreateBusRequest}> = (props) => {
          const {data} = props ?? {};

          return  createBus(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateBusMutationResult = NonNullable<Awaited<ReturnType<typeof createBus>>>
    export type CreateBusMutationBody = CreateBusRequest
    export type CreateBusMutationError = unknown

    export const useCreateBus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBus>>, TError,{data: CreateBusRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBus>>,
        TError,
        {data: CreateBusRequest},
        TContext
      > => {

      const mutationOptions = getCreateBusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    