/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTripRequest,
  DeleteTripParams,
  GetAllTripsParams,
  PagedModelTripResponse,
  SearchTripsParams,
  TripPassengerResponse,
  TripResponse,
  UpdateTripStatusParams,
  UpdateTripStopsRequest
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns details of a specific trip.
 * @summary Get trip by ID
 */
export const getTripById = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TripResponse>(
      {url: `/api/trips/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTripByIdQueryKey = (id?: string,) => {
    return [
    `/api/trips/${id}`
    ] as const;
    }

    
export const getGetTripByIdQueryOptions = <TData = Awaited<ReturnType<typeof getTripById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTripByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTripById>>> = ({ signal }) => getTripById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTripById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTripByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTripById>>>
export type GetTripByIdQueryError = unknown


export function useGetTripById<TData = Awaited<ReturnType<typeof getTripById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTripById>>,
          TError,
          Awaited<ReturnType<typeof getTripById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTripById<TData = Awaited<ReturnType<typeof getTripById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTripById>>,
          TError,
          Awaited<ReturnType<typeof getTripById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTripById<TData = Awaited<ReturnType<typeof getTripById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get trip by ID
 */

export function useGetTripById<TData = Awaited<ReturnType<typeof getTripById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTripByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Updates an existing trip.
 * @summary Update trip
 */
export const updateTrip = (
    id: string,
    createTripRequest: CreateTripRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<TripResponse>(
      {url: `/api/trips/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createTripRequest
    },
      options);
    }
  


export const getUpdateTripMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTrip>>, TError,{id: string;data: CreateTripRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTrip>>, TError,{id: string;data: CreateTripRequest}, TContext> => {

const mutationKey = ['updateTrip'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTrip>>, {id: string;data: CreateTripRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTrip(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTripMutationResult = NonNullable<Awaited<ReturnType<typeof updateTrip>>>
    export type UpdateTripMutationBody = CreateTripRequest
    export type UpdateTripMutationError = unknown

    /**
 * @summary Update trip
 */
export const useUpdateTrip = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTrip>>, TError,{id: string;data: CreateTripRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTrip>>,
        TError,
        {id: string;data: CreateTripRequest},
        TContext
      > => {

      const mutationOptions = getUpdateTripMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Deletes (or force deletes) a trip. When force is true, will also handle dependent entities.
 * @summary Delete trip
 */
export const deleteTrip = (
    id: string,
    params?: DeleteTripParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/trips/${id}`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteTripMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTrip>>, TError,{id: string;params?: DeleteTripParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTrip>>, TError,{id: string;params?: DeleteTripParams}, TContext> => {

const mutationKey = ['deleteTrip'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTrip>>, {id: string;params?: DeleteTripParams}> = (props) => {
          const {id,params} = props ?? {};

          return  deleteTrip(id,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTripMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTrip>>>
    
    export type DeleteTripMutationError = unknown

    /**
 * @summary Delete trip
 */
export const useDeleteTrip = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTrip>>, TError,{id: string;params?: DeleteTripParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTrip>>,
        TError,
        {id: string;params?: DeleteTripParams},
        TContext
      > => {

      const mutationOptions = getDeleteTripMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Updates the specific stops for a trip.
 * @summary Update trip stops
 */
export const updateTripStops = (
    id: string,
    updateTripStopsRequest: UpdateTripStopsRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<TripResponse>(
      {url: `/api/trips/${id}/stops`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateTripStopsRequest
    },
      options);
    }
  


export const getUpdateTripStopsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTripStops>>, TError,{id: string;data: UpdateTripStopsRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTripStops>>, TError,{id: string;data: UpdateTripStopsRequest}, TContext> => {

const mutationKey = ['updateTripStops'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTripStops>>, {id: string;data: UpdateTripStopsRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTripStops(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTripStopsMutationResult = NonNullable<Awaited<ReturnType<typeof updateTripStops>>>
    export type UpdateTripStopsMutationBody = UpdateTripStopsRequest
    export type UpdateTripStopsMutationError = unknown

    /**
 * @summary Update trip stops
 */
export const useUpdateTripStops = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTripStops>>, TError,{id: string;data: UpdateTripStopsRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTripStops>>,
        TError,
        {id: string;data: UpdateTripStopsRequest},
        TContext
      > => {

      const mutationOptions = getUpdateTripStopsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns a paginated list of trips.
 * @summary List trips
 */
export const getAllTrips = (
    params: GetAllTripsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PagedModelTripResponse>(
      {url: `/api/trips`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllTripsQueryKey = (params?: GetAllTripsParams,) => {
    return [
    `/api/trips`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllTripsQueryOptions = <TData = Awaited<ReturnType<typeof getAllTrips>>, TError = unknown>(params: GetAllTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllTripsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllTrips>>> = ({ signal }) => getAllTrips(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllTrips>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllTripsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllTrips>>>
export type GetAllTripsQueryError = unknown


export function useGetAllTrips<TData = Awaited<ReturnType<typeof getAllTrips>>, TError = unknown>(
 params: GetAllTripsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTrips>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTrips>>,
          TError,
          Awaited<ReturnType<typeof getAllTrips>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllTrips<TData = Awaited<ReturnType<typeof getAllTrips>>, TError = unknown>(
 params: GetAllTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTrips>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTrips>>,
          TError,
          Awaited<ReturnType<typeof getAllTrips>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllTrips<TData = Awaited<ReturnType<typeof getAllTrips>>, TError = unknown>(
 params: GetAllTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List trips
 */

export function useGetAllTrips<TData = Awaited<ReturnType<typeof getAllTrips>>, TError = unknown>(
 params: GetAllTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllTripsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Creates a new trip with pricing and schedule information.
 * @summary Create trip
 */
export const createTrip = (
    createTripRequest: CreateTripRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TripResponse>(
      {url: `/api/trips`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTripRequest, signal
    },
      options);
    }
  


export const getCreateTripMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTrip>>, TError,{data: CreateTripRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createTrip>>, TError,{data: CreateTripRequest}, TContext> => {

const mutationKey = ['createTrip'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTrip>>, {data: CreateTripRequest}> = (props) => {
          const {data} = props ?? {};

          return  createTrip(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTripMutationResult = NonNullable<Awaited<ReturnType<typeof createTrip>>>
    export type CreateTripMutationBody = CreateTripRequest
    export type CreateTripMutationError = unknown

    /**
 * @summary Create trip
 */
export const useCreateTrip = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTrip>>, TError,{data: CreateTripRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTrip>>,
        TError,
        {data: CreateTripRequest},
        TContext
      > => {

      const mutationOptions = getCreateTripMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Updates the status of a trip.
 * @summary Update trip status
 */
export const updateTripStatus = (
    id: string,
    params: UpdateTripStatusParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<TripResponse>(
      {url: `/api/trips/${id}/status`, method: 'PATCH',
        params
    },
      options);
    }
  


export const getUpdateTripStatusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTripStatus>>, TError,{id: string;params: UpdateTripStatusParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTripStatus>>, TError,{id: string;params: UpdateTripStatusParams}, TContext> => {

const mutationKey = ['updateTripStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTripStatus>>, {id: string;params: UpdateTripStatusParams}> = (props) => {
          const {id,params} = props ?? {};

          return  updateTripStatus(id,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTripStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateTripStatus>>>
    
    export type UpdateTripStatusMutationError = unknown

    /**
 * @summary Update trip status
 */
export const useUpdateTripStatus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTripStatus>>, TError,{id: string;params: UpdateTripStatusParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTripStatus>>,
        TError,
        {id: string;params: UpdateTripStatusParams},
        TContext
      > => {

      const mutationOptions = getUpdateTripStatusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns a list of passengers for a specific trip.
 * @summary Get trip passengers
 */
export const getTripPassengers = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TripPassengerResponse[]>(
      {url: `/api/trips/${id}/passengers`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTripPassengersQueryKey = (id?: string,) => {
    return [
    `/api/trips/${id}/passengers`
    ] as const;
    }

    
export const getGetTripPassengersQueryOptions = <TData = Awaited<ReturnType<typeof getTripPassengers>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripPassengers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTripPassengersQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTripPassengers>>> = ({ signal }) => getTripPassengers(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTripPassengers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTripPassengersQueryResult = NonNullable<Awaited<ReturnType<typeof getTripPassengers>>>
export type GetTripPassengersQueryError = unknown


export function useGetTripPassengers<TData = Awaited<ReturnType<typeof getTripPassengers>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripPassengers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTripPassengers>>,
          TError,
          Awaited<ReturnType<typeof getTripPassengers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTripPassengers<TData = Awaited<ReturnType<typeof getTripPassengers>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripPassengers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTripPassengers>>,
          TError,
          Awaited<ReturnType<typeof getTripPassengers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTripPassengers<TData = Awaited<ReturnType<typeof getTripPassengers>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripPassengers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get trip passengers
 */

export function useGetTripPassengers<TData = Awaited<ReturnType<typeof getTripPassengers>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripPassengers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTripPassengersQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Searches for available trips based on origin, destination and date filters.
 * @summary Search trips
 */
export const searchTrips = (
    params: SearchTripsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PagedModelTripResponse>(
      {url: `/api/trips/search`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSearchTripsQueryKey = (params?: SearchTripsParams,) => {
    return [
    `/api/trips/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchTripsQueryOptions = <TData = Awaited<ReturnType<typeof searchTrips>>, TError = unknown>(params: SearchTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchTripsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchTrips>>> = ({ signal }) => searchTrips(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchTrips>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchTripsQueryResult = NonNullable<Awaited<ReturnType<typeof searchTrips>>>
export type SearchTripsQueryError = unknown


export function useSearchTrips<TData = Awaited<ReturnType<typeof searchTrips>>, TError = unknown>(
 params: SearchTripsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTrips>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchTrips>>,
          TError,
          Awaited<ReturnType<typeof searchTrips>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchTrips<TData = Awaited<ReturnType<typeof searchTrips>>, TError = unknown>(
 params: SearchTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTrips>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchTrips>>,
          TError,
          Awaited<ReturnType<typeof searchTrips>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchTrips<TData = Awaited<ReturnType<typeof searchTrips>>, TError = unknown>(
 params: SearchTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search trips
 */

export function useSearchTrips<TData = Awaited<ReturnType<typeof searchTrips>>, TError = unknown>(
 params: SearchTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchTripsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




