/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetRecentTransactionsParams,
  GetRevenueChartParams,
  GetTopOperatorsParams,
  GetTopRoutes1Params,
  MetricsResponse,
  RevenueChartResponse,
  TopOperatorResponse,
  TopRouteResponse,
  TransactionResponse
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getTopRoutes1 = (
    params?: GetTopRoutes1Params,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TopRouteResponse[]>(
      {url: `/api/admin/dashboard/top-routes`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetTopRoutes1QueryKey = (params?: GetTopRoutes1Params,) => {
    return [
    `/api/admin/dashboard/top-routes`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetTopRoutes1QueryOptions = <TData = Awaited<ReturnType<typeof getTopRoutes1>>, TError = unknown>(params?: GetTopRoutes1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTopRoutes1QueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopRoutes1>>> = ({ signal }) => getTopRoutes1(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTopRoutes1QueryResult = NonNullable<Awaited<ReturnType<typeof getTopRoutes1>>>
export type GetTopRoutes1QueryError = unknown


export function useGetTopRoutes1<TData = Awaited<ReturnType<typeof getTopRoutes1>>, TError = unknown>(
 params: undefined |  GetTopRoutes1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopRoutes1>>,
          TError,
          Awaited<ReturnType<typeof getTopRoutes1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopRoutes1<TData = Awaited<ReturnType<typeof getTopRoutes1>>, TError = unknown>(
 params?: GetTopRoutes1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopRoutes1>>,
          TError,
          Awaited<ReturnType<typeof getTopRoutes1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopRoutes1<TData = Awaited<ReturnType<typeof getTopRoutes1>>, TError = unknown>(
 params?: GetTopRoutes1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTopRoutes1<TData = Awaited<ReturnType<typeof getTopRoutes1>>, TError = unknown>(
 params?: GetTopRoutes1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTopRoutes1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getTopOperators = (
    params?: GetTopOperatorsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TopOperatorResponse[]>(
      {url: `/api/admin/dashboard/top-operators`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetTopOperatorsQueryKey = (params?: GetTopOperatorsParams,) => {
    return [
    `/api/admin/dashboard/top-operators`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetTopOperatorsQueryOptions = <TData = Awaited<ReturnType<typeof getTopOperators>>, TError = unknown>(params?: GetTopOperatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopOperators>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTopOperatorsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopOperators>>> = ({ signal }) => getTopOperators(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTopOperators>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTopOperatorsQueryResult = NonNullable<Awaited<ReturnType<typeof getTopOperators>>>
export type GetTopOperatorsQueryError = unknown


export function useGetTopOperators<TData = Awaited<ReturnType<typeof getTopOperators>>, TError = unknown>(
 params: undefined |  GetTopOperatorsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopOperators>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopOperators>>,
          TError,
          Awaited<ReturnType<typeof getTopOperators>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopOperators<TData = Awaited<ReturnType<typeof getTopOperators>>, TError = unknown>(
 params?: GetTopOperatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopOperators>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopOperators>>,
          TError,
          Awaited<ReturnType<typeof getTopOperators>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopOperators<TData = Awaited<ReturnType<typeof getTopOperators>>, TError = unknown>(
 params?: GetTopOperatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopOperators>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTopOperators<TData = Awaited<ReturnType<typeof getTopOperators>>, TError = unknown>(
 params?: GetTopOperatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopOperators>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTopOperatorsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getRevenueChart = (
    params?: GetRevenueChartParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RevenueChartResponse[]>(
      {url: `/api/admin/dashboard/revenue`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetRevenueChartQueryKey = (params?: GetRevenueChartParams,) => {
    return [
    `/api/admin/dashboard/revenue`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRevenueChartQueryOptions = <TData = Awaited<ReturnType<typeof getRevenueChart>>, TError = unknown>(params?: GetRevenueChartParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueChart>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRevenueChartQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRevenueChart>>> = ({ signal }) => getRevenueChart(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRevenueChart>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRevenueChartQueryResult = NonNullable<Awaited<ReturnType<typeof getRevenueChart>>>
export type GetRevenueChartQueryError = unknown


export function useGetRevenueChart<TData = Awaited<ReturnType<typeof getRevenueChart>>, TError = unknown>(
 params: undefined |  GetRevenueChartParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueChart>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRevenueChart>>,
          TError,
          Awaited<ReturnType<typeof getRevenueChart>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRevenueChart<TData = Awaited<ReturnType<typeof getRevenueChart>>, TError = unknown>(
 params?: GetRevenueChartParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueChart>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRevenueChart>>,
          TError,
          Awaited<ReturnType<typeof getRevenueChart>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRevenueChart<TData = Awaited<ReturnType<typeof getRevenueChart>>, TError = unknown>(
 params?: GetRevenueChartParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueChart>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetRevenueChart<TData = Awaited<ReturnType<typeof getRevenueChart>>, TError = unknown>(
 params?: GetRevenueChartParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueChart>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRevenueChartQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getRecentTransactions = (
    params?: GetRecentTransactionsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TransactionResponse[]>(
      {url: `/api/admin/dashboard/recent-transactions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetRecentTransactionsQueryKey = (params?: GetRecentTransactionsParams,) => {
    return [
    `/api/admin/dashboard/recent-transactions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRecentTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof getRecentTransactions>>, TError = unknown>(params?: GetRecentTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecentTransactionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentTransactions>>> = ({ signal }) => getRecentTransactions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecentTransactions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRecentTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof getRecentTransactions>>>
export type GetRecentTransactionsQueryError = unknown


export function useGetRecentTransactions<TData = Awaited<ReturnType<typeof getRecentTransactions>>, TError = unknown>(
 params: undefined |  GetRecentTransactionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTransactions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentTransactions>>,
          TError,
          Awaited<ReturnType<typeof getRecentTransactions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentTransactions<TData = Awaited<ReturnType<typeof getRecentTransactions>>, TError = unknown>(
 params?: GetRecentTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTransactions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentTransactions>>,
          TError,
          Awaited<ReturnType<typeof getRecentTransactions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentTransactions<TData = Awaited<ReturnType<typeof getRecentTransactions>>, TError = unknown>(
 params?: GetRecentTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetRecentTransactions<TData = Awaited<ReturnType<typeof getRecentTransactions>>, TError = unknown>(
 params?: GetRecentTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRecentTransactionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getMetrics = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<MetricsResponse>(
      {url: `/api/admin/dashboard/metrics`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMetricsQueryKey = () => {
    return [
    `/api/admin/dashboard/metrics`
    ] as const;
    }

    
export const getGetMetricsQueryOptions = <TData = Awaited<ReturnType<typeof getMetrics>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetrics>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMetricsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMetrics>>> = ({ signal }) => getMetrics(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMetrics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMetricsQueryResult = NonNullable<Awaited<ReturnType<typeof getMetrics>>>
export type GetMetricsQueryError = unknown


export function useGetMetrics<TData = Awaited<ReturnType<typeof getMetrics>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetrics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetrics>>,
          TError,
          Awaited<ReturnType<typeof getMetrics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMetrics<TData = Awaited<ReturnType<typeof getMetrics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetrics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetrics>>,
          TError,
          Awaited<ReturnType<typeof getMetrics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMetrics<TData = Awaited<ReturnType<typeof getMetrics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetrics>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMetrics<TData = Awaited<ReturnType<typeof getMetrics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetrics>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMetricsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




