/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetRecentTripsParams,
  UserDashboardSummaryResponse,
  UserRecentTripResponse
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns high-level metrics and stats for the authenticated user.
 * @summary Get user dashboard summary
 */
export const getSummary = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserDashboardSummaryResponse>(
      {url: `/api/dashboard/user/summary`, method: 'GET', signal
    },
      options);
    }
  



export const getGetSummaryQueryKey = () => {
    return [
    `/api/dashboard/user/summary`
    ] as const;
    }

    
export const getGetSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getSummary>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSummaryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSummary>>> = ({ signal }) => getSummary(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getSummary>>>
export type GetSummaryQueryError = unknown


export function useGetSummary<TData = Awaited<ReturnType<typeof getSummary>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSummary>>,
          TError,
          Awaited<ReturnType<typeof getSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSummary<TData = Awaited<ReturnType<typeof getSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSummary>>,
          TError,
          Awaited<ReturnType<typeof getSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSummary<TData = Awaited<ReturnType<typeof getSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user dashboard summary
 */

export function useGetSummary<TData = Awaited<ReturnType<typeof getSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSummaryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns a list of the most recent trips taken by the authenticated user.
 * @summary Get recent trips
 */
export const getRecentTrips = (
    params?: GetRecentTripsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserRecentTripResponse[]>(
      {url: `/api/dashboard/user/recent-trips`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetRecentTripsQueryKey = (params?: GetRecentTripsParams,) => {
    return [
    `/api/dashboard/user/recent-trips`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRecentTripsQueryOptions = <TData = Awaited<ReturnType<typeof getRecentTrips>>, TError = unknown>(params?: GetRecentTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecentTripsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentTrips>>> = ({ signal }) => getRecentTrips(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecentTrips>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRecentTripsQueryResult = NonNullable<Awaited<ReturnType<typeof getRecentTrips>>>
export type GetRecentTripsQueryError = unknown


export function useGetRecentTrips<TData = Awaited<ReturnType<typeof getRecentTrips>>, TError = unknown>(
 params: undefined |  GetRecentTripsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTrips>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentTrips>>,
          TError,
          Awaited<ReturnType<typeof getRecentTrips>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentTrips<TData = Awaited<ReturnType<typeof getRecentTrips>>, TError = unknown>(
 params?: GetRecentTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTrips>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentTrips>>,
          TError,
          Awaited<ReturnType<typeof getRecentTrips>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentTrips<TData = Awaited<ReturnType<typeof getRecentTrips>>, TError = unknown>(
 params?: GetRecentTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get recent trips
 */

export function useGetRecentTrips<TData = Awaited<ReturnType<typeof getRecentTrips>>, TError = unknown>(
 params?: GetRecentTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRecentTripsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




