/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetSeatStatus200,
  LockSeat200,
  LockSeatRequest,
  UnlockSeat200
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Releases a previously locked seat for the current user or guest.
 * @summary Unlock a seat
 */
export const unlockSeat = (
    lockSeatRequest: LockSeatRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UnlockSeat200>(
      {url: `/api/bookings/seats/unlock`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: lockSeatRequest, signal
    },
      options);
    }
  


export const getUnlockSeatMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlockSeat>>, TError,{data: LockSeatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof unlockSeat>>, TError,{data: LockSeatRequest}, TContext> => {

const mutationKey = ['unlockSeat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unlockSeat>>, {data: LockSeatRequest}> = (props) => {
          const {data} = props ?? {};

          return  unlockSeat(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnlockSeatMutationResult = NonNullable<Awaited<ReturnType<typeof unlockSeat>>>
    export type UnlockSeatMutationBody = LockSeatRequest
    export type UnlockSeatMutationError = unknown

    /**
 * @summary Unlock a seat
 */
export const useUnlockSeat = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlockSeat>>, TError,{data: LockSeatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unlockSeat>>,
        TError,
        {data: LockSeatRequest},
        TContext
      > => {

      const mutationOptions = getUnlockSeatMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Attempts to place a temporary lock on a seat for the current user or guest.
 * @summary Lock a seat
 */
export const lockSeat = (
    lockSeatRequest: LockSeatRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LockSeat200>(
      {url: `/api/bookings/seats/lock`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: lockSeatRequest, signal
    },
      options);
    }
  


export const getLockSeatMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lockSeat>>, TError,{data: LockSeatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof lockSeat>>, TError,{data: LockSeatRequest}, TContext> => {

const mutationKey = ['lockSeat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lockSeat>>, {data: LockSeatRequest}> = (props) => {
          const {data} = props ?? {};

          return  lockSeat(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LockSeatMutationResult = NonNullable<Awaited<ReturnType<typeof lockSeat>>>
    export type LockSeatMutationBody = LockSeatRequest
    export type LockSeatMutationError = unknown

    /**
 * @summary Lock a seat
 */
export const useLockSeat = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lockSeat>>, TError,{data: LockSeatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lockSeat>>,
        TError,
        {data: LockSeatRequest},
        TContext
      > => {

      const mutationOptions = getLockSeatMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns a map of seat codes to status (BOOKED or LOCKED) for a given trip.
 * @summary Get seat status for trip
 */
export const getSeatStatus = (
    tripId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSeatStatus200>(
      {url: `/api/bookings/seats/${tripId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetSeatStatusQueryKey = (tripId?: string,) => {
    return [
    `/api/bookings/seats/${tripId}`
    ] as const;
    }

    
export const getGetSeatStatusQueryOptions = <TData = Awaited<ReturnType<typeof getSeatStatus>>, TError = unknown>(tripId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSeatStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSeatStatusQueryKey(tripId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSeatStatus>>> = ({ signal }) => getSeatStatus(tripId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(tripId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSeatStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSeatStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getSeatStatus>>>
export type GetSeatStatusQueryError = unknown


export function useGetSeatStatus<TData = Awaited<ReturnType<typeof getSeatStatus>>, TError = unknown>(
 tripId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSeatStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSeatStatus>>,
          TError,
          Awaited<ReturnType<typeof getSeatStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSeatStatus<TData = Awaited<ReturnType<typeof getSeatStatus>>, TError = unknown>(
 tripId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSeatStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSeatStatus>>,
          TError,
          Awaited<ReturnType<typeof getSeatStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSeatStatus<TData = Awaited<ReturnType<typeof getSeatStatus>>, TError = unknown>(
 tripId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSeatStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get seat status for trip
 */

export function useGetSeatStatus<TData = Awaited<ReturnType<typeof getSeatStatus>>, TError = unknown>(
 tripId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSeatStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSeatStatusQueryOptions(tripId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




