/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateStationRequest,
  DeleteStationParams,
  GetAllStationsParams,
  PagedModelStation,
  SearchStationsParams,
  Station
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const updateStation = (
    id: string,
    createStationRequest: CreateStationRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Station>(
      {url: `/api/stations/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createStationRequest
    },
      options);
    }
  


export const getUpdateStationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStation>>, TError,{id: string;data: CreateStationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateStation>>, TError,{id: string;data: CreateStationRequest}, TContext> => {

const mutationKey = ['updateStation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStation>>, {id: string;data: CreateStationRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateStation(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateStationMutationResult = NonNullable<Awaited<ReturnType<typeof updateStation>>>
    export type UpdateStationMutationBody = CreateStationRequest
    export type UpdateStationMutationError = unknown

    export const useUpdateStation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStation>>, TError,{id: string;data: CreateStationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStation>>,
        TError,
        {id: string;data: CreateStationRequest},
        TContext
      > => {

      const mutationOptions = getUpdateStationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteStation = (
    id: string,
    params?: DeleteStationParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/stations/${id}`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteStationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStation>>, TError,{id: string;params?: DeleteStationParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteStation>>, TError,{id: string;params?: DeleteStationParams}, TContext> => {

const mutationKey = ['deleteStation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStation>>, {id: string;params?: DeleteStationParams}> = (props) => {
          const {id,params} = props ?? {};

          return  deleteStation(id,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteStationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteStation>>>
    
    export type DeleteStationMutationError = unknown

    export const useDeleteStation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStation>>, TError,{id: string;params?: DeleteStationParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteStation>>,
        TError,
        {id: string;params?: DeleteStationParams},
        TContext
      > => {

      const mutationOptions = getDeleteStationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllStations = (
    params: GetAllStationsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PagedModelStation>(
      {url: `/api/stations`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllStationsQueryKey = (params?: GetAllStationsParams,) => {
    return [
    `/api/stations`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllStationsQueryOptions = <TData = Awaited<ReturnType<typeof getAllStations>>, TError = unknown>(params: GetAllStationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllStations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllStationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllStations>>> = ({ signal }) => getAllStations(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllStations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllStationsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllStations>>>
export type GetAllStationsQueryError = unknown


export function useGetAllStations<TData = Awaited<ReturnType<typeof getAllStations>>, TError = unknown>(
 params: GetAllStationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllStations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllStations>>,
          TError,
          Awaited<ReturnType<typeof getAllStations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllStations<TData = Awaited<ReturnType<typeof getAllStations>>, TError = unknown>(
 params: GetAllStationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllStations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllStations>>,
          TError,
          Awaited<ReturnType<typeof getAllStations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllStations<TData = Awaited<ReturnType<typeof getAllStations>>, TError = unknown>(
 params: GetAllStationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllStations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllStations<TData = Awaited<ReturnType<typeof getAllStations>>, TError = unknown>(
 params: GetAllStationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllStations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllStationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createStation = (
    createStationRequest: CreateStationRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Station>(
      {url: `/api/stations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createStationRequest, signal
    },
      options);
    }
  


export const getCreateStationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStation>>, TError,{data: CreateStationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createStation>>, TError,{data: CreateStationRequest}, TContext> => {

const mutationKey = ['createStation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStation>>, {data: CreateStationRequest}> = (props) => {
          const {data} = props ?? {};

          return  createStation(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateStationMutationResult = NonNullable<Awaited<ReturnType<typeof createStation>>>
    export type CreateStationMutationBody = CreateStationRequest
    export type CreateStationMutationError = unknown

    export const useCreateStation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStation>>, TError,{data: CreateStationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStation>>,
        TError,
        {data: CreateStationRequest},
        TContext
      > => {

      const mutationOptions = getCreateStationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const searchStations = (
    params: SearchStationsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PagedModelStation>(
      {url: `/api/stations/search`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSearchStationsQueryKey = (params?: SearchStationsParams,) => {
    return [
    `/api/stations/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchStationsQueryOptions = <TData = Awaited<ReturnType<typeof searchStations>>, TError = unknown>(params: SearchStationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchStations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchStationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchStations>>> = ({ signal }) => searchStations(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchStations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchStationsQueryResult = NonNullable<Awaited<ReturnType<typeof searchStations>>>
export type SearchStationsQueryError = unknown


export function useSearchStations<TData = Awaited<ReturnType<typeof searchStations>>, TError = unknown>(
 params: SearchStationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchStations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchStations>>,
          TError,
          Awaited<ReturnType<typeof searchStations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchStations<TData = Awaited<ReturnType<typeof searchStations>>, TError = unknown>(
 params: SearchStationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchStations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchStations>>,
          TError,
          Awaited<ReturnType<typeof searchStations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchStations<TData = Awaited<ReturnType<typeof searchStations>>, TError = unknown>(
 params: SearchStationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchStations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchStations<TData = Awaited<ReturnType<typeof searchStations>>, TError = unknown>(
 params: SearchStationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchStations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchStationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




