/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */

/**
 * Aggregated booking counts for a time bucket within a given range.
 */
export interface BookingTrendResponse {
  /** Time bucket label returned by the database (e.g. 2025-01-01 or 2025-01-01 00:00:00). */
  bucket?: string;
  /** Total bookings created in this bucket (all statuses). */
  totalBookings?: number;
  /** Confirmed bookings created in this bucket. */
  confirmedBookings?: number;
}
