/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import type { BookingResponseStatus } from './bookingResponseStatus';
import type { TripInfo } from './tripInfo';
import type { TicketInfo } from './ticketInfo';

export interface BookingResponse {
  id?: string;
  code?: string;
  status?: BookingResponseStatus;
  totalPrice?: number;
  passengerName?: string;
  passengerPhone?: string;
  createdAt?: string;
  updatedAt?: string;
  trip?: TripInfo;
  tickets?: TicketInfo[];
}
