/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */

/**
 * Booking conversion metrics for a given time range.
 */
export interface BookingConversionResponse {
  /** Total number of bookings created in the range. */
  total?: number;
  /** Number of confirmed bookings created in the range. */
  confirmed?: number;
  /** Conversion rate = confirmed / total. When total is 0, conversionRate is 0. */
  conversionRate?: number;
}
