/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import type { TicketRequest } from './ticketRequest';

export interface CreateBookingRequest {
  tripId: string;
  userId?: string;
  /** @minLength 1 */
  passengerName: string;
  /** @minLength 1 */
  passengerPhone: string;
  passengerEmail?: string;
  pickupStationId?: string;
  dropoffStationId?: string;
  totalPrice: number;
  /** @minItems 1 */
  tickets: TicketRequest[];
}
