/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import type { SummaryMetric } from './summaryMetric';
import type { ActivityItem } from './activityItem';
import type { RoleWidget } from './roleWidget';

export interface DashboardResponse {
  summary?: SummaryMetric[];
  activity?: ActivityItem[];
  roleWidgets?: RoleWidget;
}
