/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import type { GetBookingTrendsGroupBy } from './getBookingTrendsGroupBy';

export type GetBookingTrendsParams = {
/**
 * Start of the time range (inclusive). ISO-8601 date-time.
 */
from?: string;
/**
 * End of the time range (inclusive). ISO-8601 date-time.
 */
to?: string;
/**
 * Time bucket grouping.
 */
groupBy?: GetBookingTrendsGroupBy;
};
