/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */

export type GetBookingTrendsGroupBy = typeof GetBookingTrendsGroupBy[keyof typeof GetBookingTrendsGroupBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetBookingTrendsGroupBy = {
  day: 'day',
  week: 'week',
} as const;
