/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */

export type GetRevenueChartParams = {
/**
 * Start of the time range (inclusive). ISO-8601 date-time, e.g. 2025-01-01T00:00:00Z.
 */
from?: string;
/**
 * End of the time range (inclusive). ISO-8601 date-time, e.g. 2025-01-07T23:59:59Z.
 */
to?: string;
};
