/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */

export type GetTopOperatorsParams = {
/**
 * Start of the time range (inclusive). When omitted, returns all-time top operators.
 */
from?: string;
/**
 * End of the time range (inclusive). When omitted, returns all-time top operators.
 */
to?: string;
/**
 * Max number of operators to return.
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
