/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import type { Station } from './station';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelStation {
  content?: Station[];
  page?: PageMetadata;
}
