/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */

export type PaymentResponseStatus = typeof PaymentResponseStatus[keyof typeof PaymentResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentResponseStatus = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;
