/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import type { PaymentResponseStatus } from './paymentResponseStatus';

export interface PaymentResponse {
  id?: string;
  bookingId?: string;
  orderCode?: number;
  amount?: number;
  status?: PaymentResponseStatus;
  checkoutUrl?: string;
  qrCode?: string;
  createdAt?: string;
  updatedAt?: string;
}
