/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */

export interface ResetPasswordRequest {
  /** @minLength 1 */
  token: string;
  /**
   * @minLength 6
   * @maxLength 2147483647
   */
  newPassword: string;
}
