/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import type { UserInfo } from './userInfo';
import type { RouteInfo } from './routeInfo';

export interface ReviewResponse {
  id?: string;
  rating?: number;
  comment?: string;
  createdAt?: string;
  user?: UserInfo;
  route?: RouteInfo;
  tripDate?: string;
}
