/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import type { StationInfo } from './stationInfo';

export interface RouteStopInfo {
  id?: string;
  station?: StationInfo;
  customName?: string;
  customAddress?: string;
  stopOrder?: number;
  durationMinutesFromOrigin?: number;
  stopType?: string;
}
