/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import type { Route } from './route';
import type { Station } from './station';
import type { RouteStopStopType } from './routeStopStopType';

export interface RouteStop {
  id?: string;
  route?: Route;
  station?: Station;
  stopOrder?: number;
  durationMinutesFromOrigin?: number;
  defaultSurcharge?: number;
  stopType?: RouteStopStopType;
}
