/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import type { StationInfo } from './stationInfo';
import type { RouteStopInfo } from './routeStopInfo';

export interface RouteInfo {
  id?: string;
  originStation?: StationInfo;
  destinationStation?: StationInfo;
  durationMinutes?: number;
  stops?: RouteStopInfo[];
}
