/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */

export interface SearchTripRequest {
  origin?: string;
  destination?: string;
  date?: string;
  minTime?: string;
  maxTime?: string;
  minPrice?: number;
  maxPrice?: number;
  amenities?: string[];
  operatorIds?: string[];
  sortBy?: string;
  page?: number;
  size?: number;
}
