/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */

export interface TicketRequest {
  /** @minLength 1 */
  seatCode: string;
  /** @minLength 1 */
  passengerName: string;
  /** @minLength 1 */
  passengerPhone: string;
  price: number;
}
