/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import type { TripPassengerResponseBookingStatus } from './tripPassengerResponseBookingStatus';

export interface TripPassengerResponse {
  ticketId?: string;
  bookingCode?: string;
  passengerName?: string;
  passengerPhone?: string;
  seatCode?: string;
  bookingStatus?: TripPassengerResponseBookingStatus;
  pickupStation?: string;
  dropoffStation?: string;
  boarded?: boolean;
}
