/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */

export type TripPassengerResponseBookingStatus = typeof TripPassengerResponseBookingStatus[keyof typeof TripPassengerResponseBookingStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TripPassengerResponseBookingStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
} as const;
