/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import type { UserResponseRole } from './userResponseRole';

export interface UserResponse {
  id?: string;
  fullName?: string;
  email?: string;
  role?: UserResponseRole;
  avatarUrl?: string;
}
