/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BusLayout,
  BusLayoutRequest,
  BusLayoutResponse,
  SeatUpdatePayload
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getLayout = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BusLayoutResponse>(
      {url: `/api/bus-layouts/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetLayoutQueryKey = (id?: string,) => {
    return [
    `/api/bus-layouts/${id}`
    ] as const;
    }

    
export const getGetLayoutQueryOptions = <TData = Awaited<ReturnType<typeof getLayout>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLayout>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLayoutQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLayout>>> = ({ signal }) => getLayout(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLayout>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLayoutQueryResult = NonNullable<Awaited<ReturnType<typeof getLayout>>>
export type GetLayoutQueryError = unknown


export function useGetLayout<TData = Awaited<ReturnType<typeof getLayout>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLayout>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLayout>>,
          TError,
          Awaited<ReturnType<typeof getLayout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLayout<TData = Awaited<ReturnType<typeof getLayout>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLayout>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLayout>>,
          TError,
          Awaited<ReturnType<typeof getLayout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLayout<TData = Awaited<ReturnType<typeof getLayout>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLayout>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLayout<TData = Awaited<ReturnType<typeof getLayout>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLayout>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLayoutQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateLayoutMetadata = (
    id: string,
    busLayoutRequest: BusLayoutRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<BusLayout>(
      {url: `/api/bus-layouts/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: busLayoutRequest
    },
      options);
    }
  


export const getUpdateLayoutMetadataMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLayoutMetadata>>, TError,{id: string;data: BusLayoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateLayoutMetadata>>, TError,{id: string;data: BusLayoutRequest}, TContext> => {

const mutationKey = ['updateLayoutMetadata'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLayoutMetadata>>, {id: string;data: BusLayoutRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLayoutMetadata(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateLayoutMetadataMutationResult = NonNullable<Awaited<ReturnType<typeof updateLayoutMetadata>>>
    export type UpdateLayoutMetadataMutationBody = BusLayoutRequest
    export type UpdateLayoutMetadataMutationError = unknown

    export const useUpdateLayoutMetadata = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLayoutMetadata>>, TError,{id: string;data: BusLayoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLayoutMetadata>>,
        TError,
        {id: string;data: BusLayoutRequest},
        TContext
      > => {

      const mutationOptions = getUpdateLayoutMetadataMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteLayout = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/bus-layouts/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteLayoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLayout>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteLayout>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteLayout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLayout>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteLayout(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteLayoutMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLayout>>>
    
    export type DeleteLayoutMutationError = unknown

    export const useDeleteLayout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLayout>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLayout>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteLayoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateLayoutSeats = (
    id: string,
    seatUpdatePayload: SeatUpdatePayload,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/bus-layouts/${id}/seats`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: seatUpdatePayload
    },
      options);
    }
  


export const getUpdateLayoutSeatsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLayoutSeats>>, TError,{id: string;data: SeatUpdatePayload}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateLayoutSeats>>, TError,{id: string;data: SeatUpdatePayload}, TContext> => {

const mutationKey = ['updateLayoutSeats'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLayoutSeats>>, {id: string;data: SeatUpdatePayload}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLayoutSeats(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateLayoutSeatsMutationResult = NonNullable<Awaited<ReturnType<typeof updateLayoutSeats>>>
    export type UpdateLayoutSeatsMutationBody = SeatUpdatePayload
    export type UpdateLayoutSeatsMutationError = unknown

    export const useUpdateLayoutSeats = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLayoutSeats>>, TError,{id: string;data: SeatUpdatePayload}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLayoutSeats>>,
        TError,
        {id: string;data: SeatUpdatePayload},
        TContext
      > => {

      const mutationOptions = getUpdateLayoutSeatsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllLayouts = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BusLayoutResponse[]>(
      {url: `/api/bus-layouts`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAllLayoutsQueryKey = () => {
    return [
    `/api/bus-layouts`
    ] as const;
    }

    
export const getGetAllLayoutsQueryOptions = <TData = Awaited<ReturnType<typeof getAllLayouts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLayouts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllLayoutsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLayouts>>> = ({ signal }) => getAllLayouts(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllLayouts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllLayoutsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllLayouts>>>
export type GetAllLayoutsQueryError = unknown


export function useGetAllLayouts<TData = Awaited<ReturnType<typeof getAllLayouts>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLayouts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLayouts>>,
          TError,
          Awaited<ReturnType<typeof getAllLayouts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllLayouts<TData = Awaited<ReturnType<typeof getAllLayouts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLayouts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLayouts>>,
          TError,
          Awaited<ReturnType<typeof getAllLayouts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllLayouts<TData = Awaited<ReturnType<typeof getAllLayouts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLayouts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllLayouts<TData = Awaited<ReturnType<typeof getAllLayouts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLayouts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllLayoutsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createLayout = (
    busLayoutRequest: BusLayoutRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BusLayout>(
      {url: `/api/bus-layouts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: busLayoutRequest, signal
    },
      options);
    }
  


export const getCreateLayoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLayout>>, TError,{data: BusLayoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createLayout>>, TError,{data: BusLayoutRequest}, TContext> => {

const mutationKey = ['createLayout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLayout>>, {data: BusLayoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  createLayout(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateLayoutMutationResult = NonNullable<Awaited<ReturnType<typeof createLayout>>>
    export type CreateLayoutMutationBody = BusLayoutRequest
    export type CreateLayoutMutationError = unknown

    export const useCreateLayout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLayout>>, TError,{data: BusLayoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createLayout>>,
        TError,
        {data: BusLayoutRequest},
        TContext
      > => {

      const mutationOptions = getCreateLayoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    