/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ChatRequest,
  ChatResponse
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Send a message to the AI assistant and get a response.
 * @summary Chat with AI Assistant
 */
export const chat = (
    chatRequest: ChatRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ChatResponse>(
      {url: `/api/v1/ai/chat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: chatRequest, signal
    },
      options);
    }
  


export const getChatMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chat>>, TError,{data: ChatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof chat>>, TError,{data: ChatRequest}, TContext> => {

const mutationKey = ['chat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof chat>>, {data: ChatRequest}> = (props) => {
          const {data} = props ?? {};

          return  chat(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChatMutationResult = NonNullable<Awaited<ReturnType<typeof chat>>>
    export type ChatMutationBody = ChatRequest
    export type ChatMutationError = unknown

    /**
 * @summary Chat with AI Assistant
 */
export const useChat = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chat>>, TError,{data: ChatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof chat>>,
        TError,
        {data: ChatRequest},
        TContext
      > => {

      const mutationOptions = getChatMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    