/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponsePageReviewResponse,
  ApiResponseReviewResponse,
  CreateReviewRequest,
  GetReviewsByOperatorParams
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Creates a new review for a completed trip. User must own the booking, trip must be COMPLETED, and booking must be CONFIRMED.
 * @summary Create review
 */
export const createReview = (
    createReviewRequest: CreateReviewRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseReviewResponse>(
      {url: `/api/reviews`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createReviewRequest, signal
    },
      options);
    }
  


export const getCreateReviewMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReview>>, TError,{data: CreateReviewRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createReview>>, TError,{data: CreateReviewRequest}, TContext> => {

const mutationKey = ['createReview'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReview>>, {data: CreateReviewRequest}> = (props) => {
          const {data} = props ?? {};

          return  createReview(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateReviewMutationResult = NonNullable<Awaited<ReturnType<typeof createReview>>>
    export type CreateReviewMutationBody = CreateReviewRequest
    export type CreateReviewMutationError = unknown

    /**
 * @summary Create review
 */
export const useCreateReview = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReview>>, TError,{data: CreateReviewRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createReview>>,
        TError,
        {data: CreateReviewRequest},
        TContext
      > => {

      const mutationOptions = getCreateReviewMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns a paginated list of reviews for a specific bus operator.
 * @summary Get reviews by operator
 */
export const getReviewsByOperator = (
    operatorId: string,
    params: GetReviewsByOperatorParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponsePageReviewResponse>(
      {url: `/api/reviews/operator/${operatorId}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetReviewsByOperatorQueryKey = (operatorId?: string,
    params?: GetReviewsByOperatorParams,) => {
    return [
    `/api/reviews/operator/${operatorId}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetReviewsByOperatorQueryOptions = <TData = Awaited<ReturnType<typeof getReviewsByOperator>>, TError = unknown>(operatorId: string,
    params: GetReviewsByOperatorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOperator>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReviewsByOperatorQueryKey(operatorId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReviewsByOperator>>> = ({ signal }) => getReviewsByOperator(operatorId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(operatorId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOperator>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReviewsByOperatorQueryResult = NonNullable<Awaited<ReturnType<typeof getReviewsByOperator>>>
export type GetReviewsByOperatorQueryError = unknown


export function useGetReviewsByOperator<TData = Awaited<ReturnType<typeof getReviewsByOperator>>, TError = unknown>(
 operatorId: string,
    params: GetReviewsByOperatorParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOperator>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReviewsByOperator>>,
          TError,
          Awaited<ReturnType<typeof getReviewsByOperator>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReviewsByOperator<TData = Awaited<ReturnType<typeof getReviewsByOperator>>, TError = unknown>(
 operatorId: string,
    params: GetReviewsByOperatorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOperator>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReviewsByOperator>>,
          TError,
          Awaited<ReturnType<typeof getReviewsByOperator>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReviewsByOperator<TData = Awaited<ReturnType<typeof getReviewsByOperator>>, TError = unknown>(
 operatorId: string,
    params: GetReviewsByOperatorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOperator>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get reviews by operator
 */

export function useGetReviewsByOperator<TData = Awaited<ReturnType<typeof getReviewsByOperator>>, TError = unknown>(
 operatorId: string,
    params: GetReviewsByOperatorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewsByOperator>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReviewsByOperatorQueryOptions(operatorId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns the review for a specific booking if it exists.
 * @summary Get review by booking ID
 */
export const getReviewByBookingId = (
    bookingId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseReviewResponse>(
      {url: `/api/reviews/booking/${bookingId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetReviewByBookingIdQueryKey = (bookingId?: string,) => {
    return [
    `/api/reviews/booking/${bookingId}`
    ] as const;
    }

    
export const getGetReviewByBookingIdQueryOptions = <TData = Awaited<ReturnType<typeof getReviewByBookingId>>, TError = unknown>(bookingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewByBookingId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReviewByBookingIdQueryKey(bookingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReviewByBookingId>>> = ({ signal }) => getReviewByBookingId(bookingId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(bookingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReviewByBookingId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReviewByBookingIdQueryResult = NonNullable<Awaited<ReturnType<typeof getReviewByBookingId>>>
export type GetReviewByBookingIdQueryError = unknown


export function useGetReviewByBookingId<TData = Awaited<ReturnType<typeof getReviewByBookingId>>, TError = unknown>(
 bookingId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewByBookingId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReviewByBookingId>>,
          TError,
          Awaited<ReturnType<typeof getReviewByBookingId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReviewByBookingId<TData = Awaited<ReturnType<typeof getReviewByBookingId>>, TError = unknown>(
 bookingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewByBookingId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReviewByBookingId>>,
          TError,
          Awaited<ReturnType<typeof getReviewByBookingId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReviewByBookingId<TData = Awaited<ReturnType<typeof getReviewByBookingId>>, TError = unknown>(
 bookingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewByBookingId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get review by booking ID
 */

export function useGetReviewByBookingId<TData = Awaited<ReturnType<typeof getReviewByBookingId>>, TError = unknown>(
 bookingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReviewByBookingId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReviewByBookingIdQueryOptions(bookingId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




