/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddRouteStopRequest,
  CreateRouteRequest,
  DeleteRouteParams,
  GetAllRoutesParams,
  PagedModelRouteResponse,
  Route,
  RouteResponse
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const updateRoute = (
    id: string,
    createRouteRequest: CreateRouteRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Route>(
      {url: `/api/routes/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createRouteRequest
    },
      options);
    }
  


export const getUpdateRouteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRoute>>, TError,{id: string;data: CreateRouteRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateRoute>>, TError,{id: string;data: CreateRouteRequest}, TContext> => {

const mutationKey = ['updateRoute'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRoute>>, {id: string;data: CreateRouteRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRoute(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRouteMutationResult = NonNullable<Awaited<ReturnType<typeof updateRoute>>>
    export type UpdateRouteMutationBody = CreateRouteRequest
    export type UpdateRouteMutationError = unknown

    export const useUpdateRoute = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRoute>>, TError,{id: string;data: CreateRouteRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRoute>>,
        TError,
        {id: string;data: CreateRouteRequest},
        TContext
      > => {

      const mutationOptions = getUpdateRouteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteRoute = (
    id: string,
    params?: DeleteRouteParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/routes/${id}`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteRouteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRoute>>, TError,{id: string;params?: DeleteRouteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRoute>>, TError,{id: string;params?: DeleteRouteParams}, TContext> => {

const mutationKey = ['deleteRoute'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRoute>>, {id: string;params?: DeleteRouteParams}> = (props) => {
          const {id,params} = props ?? {};

          return  deleteRoute(id,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRouteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRoute>>>
    
    export type DeleteRouteMutationError = unknown

    export const useDeleteRoute = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRoute>>, TError,{id: string;params?: DeleteRouteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRoute>>,
        TError,
        {id: string;params?: DeleteRouteParams},
        TContext
      > => {

      const mutationOptions = getDeleteRouteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllRoutes = (
    params: GetAllRoutesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PagedModelRouteResponse>(
      {url: `/api/routes`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllRoutesQueryKey = (params?: GetAllRoutesParams,) => {
    return [
    `/api/routes`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllRoutesQueryOptions = <TData = Awaited<ReturnType<typeof getAllRoutes>>, TError = unknown>(params: GetAllRoutesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRoutes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllRoutesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllRoutes>>> = ({ signal }) => getAllRoutes(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllRoutes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllRoutesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllRoutes>>>
export type GetAllRoutesQueryError = unknown


export function useGetAllRoutes<TData = Awaited<ReturnType<typeof getAllRoutes>>, TError = unknown>(
 params: GetAllRoutesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRoutes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllRoutes>>,
          TError,
          Awaited<ReturnType<typeof getAllRoutes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllRoutes<TData = Awaited<ReturnType<typeof getAllRoutes>>, TError = unknown>(
 params: GetAllRoutesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRoutes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllRoutes>>,
          TError,
          Awaited<ReturnType<typeof getAllRoutes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllRoutes<TData = Awaited<ReturnType<typeof getAllRoutes>>, TError = unknown>(
 params: GetAllRoutesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRoutes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllRoutes<TData = Awaited<ReturnType<typeof getAllRoutes>>, TError = unknown>(
 params: GetAllRoutesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRoutes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllRoutesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createRoute = (
    createRouteRequest: CreateRouteRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Route>(
      {url: `/api/routes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRouteRequest, signal
    },
      options);
    }
  


export const getCreateRouteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRoute>>, TError,{data: CreateRouteRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createRoute>>, TError,{data: CreateRouteRequest}, TContext> => {

const mutationKey = ['createRoute'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRoute>>, {data: CreateRouteRequest}> = (props) => {
          const {data} = props ?? {};

          return  createRoute(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRouteMutationResult = NonNullable<Awaited<ReturnType<typeof createRoute>>>
    export type CreateRouteMutationBody = CreateRouteRequest
    export type CreateRouteMutationError = unknown

    export const useCreateRoute = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRoute>>, TError,{data: CreateRouteRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRoute>>,
        TError,
        {data: CreateRouteRequest},
        TContext
      > => {

      const mutationOptions = getCreateRouteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const addRouteStop = (
    id: string,
    addRouteStopRequest: AddRouteStopRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RouteResponse>(
      {url: `/api/routes/${id}/stops`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addRouteStopRequest, signal
    },
      options);
    }
  


export const getAddRouteStopMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addRouteStop>>, TError,{id: string;data: AddRouteStopRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof addRouteStop>>, TError,{id: string;data: AddRouteStopRequest}, TContext> => {

const mutationKey = ['addRouteStop'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addRouteStop>>, {id: string;data: AddRouteStopRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  addRouteStop(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddRouteStopMutationResult = NonNullable<Awaited<ReturnType<typeof addRouteStop>>>
    export type AddRouteStopMutationBody = AddRouteStopRequest
    export type AddRouteStopMutationError = unknown

    export const useAddRouteStop = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addRouteStop>>, TError,{id: string;data: AddRouteStopRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addRouteStop>>,
        TError,
        {id: string;data: AddRouteStopRequest},
        TContext
      > => {

      const mutationOptions = getAddRouteStopMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getTopRoutes = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RouteResponse[]>(
      {url: `/api/routes/top`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTopRoutesQueryKey = () => {
    return [
    `/api/routes/top`
    ] as const;
    }

    
export const getGetTopRoutesQueryOptions = <TData = Awaited<ReturnType<typeof getTopRoutes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTopRoutesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopRoutes>>> = ({ signal }) => getTopRoutes(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTopRoutesQueryResult = NonNullable<Awaited<ReturnType<typeof getTopRoutes>>>
export type GetTopRoutesQueryError = unknown


export function useGetTopRoutes<TData = Awaited<ReturnType<typeof getTopRoutes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopRoutes>>,
          TError,
          Awaited<ReturnType<typeof getTopRoutes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopRoutes<TData = Awaited<ReturnType<typeof getTopRoutes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopRoutes>>,
          TError,
          Awaited<ReturnType<typeof getTopRoutes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopRoutes<TData = Awaited<ReturnType<typeof getTopRoutes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTopRoutes<TData = Awaited<ReturnType<typeof getTopRoutes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTopRoutesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteRouteStop = (
    id: string,
    stopId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/routes/${id}/stops/${stopId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteRouteStopMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRouteStop>>, TError,{id: string;stopId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRouteStop>>, TError,{id: string;stopId: string}, TContext> => {

const mutationKey = ['deleteRouteStop'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRouteStop>>, {id: string;stopId: string}> = (props) => {
          const {id,stopId} = props ?? {};

          return  deleteRouteStop(id,stopId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRouteStopMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRouteStop>>>
    
    export type DeleteRouteStopMutationError = unknown

    export const useDeleteRouteStop = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRouteStop>>, TError,{id: string;stopId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRouteStop>>,
        TError,
        {id: string;stopId: string},
        TContext
      > => {

      const mutationOptions = getDeleteRouteStopMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    