/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BookingConversionResponse,
  BookingTrendResponse,
  GetBookingConversionParams,
  GetBookingTrendsParams,
  GetRecentTransactionsParams,
  GetRevenueChartParams,
  GetTopOperatorsParams,
  GetTopRoutes1Params,
  MetricsResponse,
  RevenueChartResponse,
  TopOperatorResponse,
  TopRouteResponse,
  TransactionResponse
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the top routes by tickets sold (CONFIRMED bookings), ordered descending.
 * @summary Get top routes
 */
export const getTopRoutes1 = (
    params?: GetTopRoutes1Params,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TopRouteResponse[]>(
      {url: `/api/admin/dashboard/top-routes`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetTopRoutes1QueryKey = (params?: GetTopRoutes1Params,) => {
    return [
    `/api/admin/dashboard/top-routes`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetTopRoutes1QueryOptions = <TData = Awaited<ReturnType<typeof getTopRoutes1>>, TError = string>(params?: GetTopRoutes1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTopRoutes1QueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopRoutes1>>> = ({ signal }) => getTopRoutes1(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTopRoutes1QueryResult = NonNullable<Awaited<ReturnType<typeof getTopRoutes1>>>
export type GetTopRoutes1QueryError = string


export function useGetTopRoutes1<TData = Awaited<ReturnType<typeof getTopRoutes1>>, TError = string>(
 params: undefined |  GetTopRoutes1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopRoutes1>>,
          TError,
          Awaited<ReturnType<typeof getTopRoutes1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopRoutes1<TData = Awaited<ReturnType<typeof getTopRoutes1>>, TError = string>(
 params?: GetTopRoutes1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopRoutes1>>,
          TError,
          Awaited<ReturnType<typeof getTopRoutes1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopRoutes1<TData = Awaited<ReturnType<typeof getTopRoutes1>>, TError = string>(
 params?: GetTopRoutes1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get top routes
 */

export function useGetTopRoutes1<TData = Awaited<ReturnType<typeof getTopRoutes1>>, TError = string>(
 params?: GetTopRoutes1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopRoutes1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTopRoutes1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns the top operators by tickets sold (CONFIRMED bookings), including total revenue.
 * @summary Get top operators
 */
export const getTopOperators = (
    params?: GetTopOperatorsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TopOperatorResponse[]>(
      {url: `/api/admin/dashboard/top-operators`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetTopOperatorsQueryKey = (params?: GetTopOperatorsParams,) => {
    return [
    `/api/admin/dashboard/top-operators`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetTopOperatorsQueryOptions = <TData = Awaited<ReturnType<typeof getTopOperators>>, TError = string>(params?: GetTopOperatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopOperators>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTopOperatorsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopOperators>>> = ({ signal }) => getTopOperators(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTopOperators>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTopOperatorsQueryResult = NonNullable<Awaited<ReturnType<typeof getTopOperators>>>
export type GetTopOperatorsQueryError = string


export function useGetTopOperators<TData = Awaited<ReturnType<typeof getTopOperators>>, TError = string>(
 params: undefined |  GetTopOperatorsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopOperators>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopOperators>>,
          TError,
          Awaited<ReturnType<typeof getTopOperators>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopOperators<TData = Awaited<ReturnType<typeof getTopOperators>>, TError = string>(
 params?: GetTopOperatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopOperators>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopOperators>>,
          TError,
          Awaited<ReturnType<typeof getTopOperators>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopOperators<TData = Awaited<ReturnType<typeof getTopOperators>>, TError = string>(
 params?: GetTopOperatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopOperators>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get top operators
 */

export function useGetTopOperators<TData = Awaited<ReturnType<typeof getTopOperators>>, TError = string>(
 params?: GetTopOperatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopOperators>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTopOperatorsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns a time series of revenue grouped by day over the provided [from,to] range. Defaults to the last 7 days when omitted.
 * @summary Get revenue chart series
 */
export const getRevenueChart = (
    params?: GetRevenueChartParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RevenueChartResponse[]>(
      {url: `/api/admin/dashboard/revenue`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetRevenueChartQueryKey = (params?: GetRevenueChartParams,) => {
    return [
    `/api/admin/dashboard/revenue`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRevenueChartQueryOptions = <TData = Awaited<ReturnType<typeof getRevenueChart>>, TError = string>(params?: GetRevenueChartParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueChart>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRevenueChartQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRevenueChart>>> = ({ signal }) => getRevenueChart(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRevenueChart>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRevenueChartQueryResult = NonNullable<Awaited<ReturnType<typeof getRevenueChart>>>
export type GetRevenueChartQueryError = string


export function useGetRevenueChart<TData = Awaited<ReturnType<typeof getRevenueChart>>, TError = string>(
 params: undefined |  GetRevenueChartParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueChart>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRevenueChart>>,
          TError,
          Awaited<ReturnType<typeof getRevenueChart>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRevenueChart<TData = Awaited<ReturnType<typeof getRevenueChart>>, TError = string>(
 params?: GetRevenueChartParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueChart>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRevenueChart>>,
          TError,
          Awaited<ReturnType<typeof getRevenueChart>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRevenueChart<TData = Awaited<ReturnType<typeof getRevenueChart>>, TError = string>(
 params?: GetRevenueChartParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueChart>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get revenue chart series
 */

export function useGetRevenueChart<TData = Awaited<ReturnType<typeof getRevenueChart>>, TError = string>(
 params?: GetRevenueChartParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueChart>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRevenueChartQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns the most recent bookings (latest createdAt first).
 * @summary Get recent transactions
 */
export const getRecentTransactions = (
    params?: GetRecentTransactionsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TransactionResponse[]>(
      {url: `/api/admin/dashboard/recent-transactions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetRecentTransactionsQueryKey = (params?: GetRecentTransactionsParams,) => {
    return [
    `/api/admin/dashboard/recent-transactions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRecentTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof getRecentTransactions>>, TError = string>(params?: GetRecentTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecentTransactionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentTransactions>>> = ({ signal }) => getRecentTransactions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecentTransactions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRecentTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof getRecentTransactions>>>
export type GetRecentTransactionsQueryError = string


export function useGetRecentTransactions<TData = Awaited<ReturnType<typeof getRecentTransactions>>, TError = string>(
 params: undefined |  GetRecentTransactionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTransactions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentTransactions>>,
          TError,
          Awaited<ReturnType<typeof getRecentTransactions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentTransactions<TData = Awaited<ReturnType<typeof getRecentTransactions>>, TError = string>(
 params?: GetRecentTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTransactions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentTransactions>>,
          TError,
          Awaited<ReturnType<typeof getRecentTransactions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentTransactions<TData = Awaited<ReturnType<typeof getRecentTransactions>>, TError = string>(
 params?: GetRecentTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get recent transactions
 */

export function useGetRecentTransactions<TData = Awaited<ReturnType<typeof getRecentTransactions>>, TError = string>(
 params?: GetRecentTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRecentTransactionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns high-level KPIs for today (revenue, tickets sold, active operators, new users).
 * @summary Get admin dashboard KPI metrics
 */
export const getMetrics = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<MetricsResponse>(
      {url: `/api/admin/dashboard/metrics`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMetricsQueryKey = () => {
    return [
    `/api/admin/dashboard/metrics`
    ] as const;
    }

    
export const getGetMetricsQueryOptions = <TData = Awaited<ReturnType<typeof getMetrics>>, TError = string>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetrics>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMetricsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMetrics>>> = ({ signal }) => getMetrics(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMetrics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMetricsQueryResult = NonNullable<Awaited<ReturnType<typeof getMetrics>>>
export type GetMetricsQueryError = string


export function useGetMetrics<TData = Awaited<ReturnType<typeof getMetrics>>, TError = string>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetrics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetrics>>,
          TError,
          Awaited<ReturnType<typeof getMetrics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMetrics<TData = Awaited<ReturnType<typeof getMetrics>>, TError = string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetrics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMetrics>>,
          TError,
          Awaited<ReturnType<typeof getMetrics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMetrics<TData = Awaited<ReturnType<typeof getMetrics>>, TError = string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetrics>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get admin dashboard KPI metrics
 */

export function useGetMetrics<TData = Awaited<ReturnType<typeof getMetrics>>, TError = string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMetrics>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMetricsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns booking volume trends (total bookings and confirmed bookings) grouped by day or week over the provided [from,to] range. Defaults to the last 30 days when omitted.
 * @summary Get booking trends
 */
export const getBookingTrends = (
    params?: GetBookingTrendsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BookingTrendResponse[]>(
      {url: `/api/admin/dashboard/booking-trends`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetBookingTrendsQueryKey = (params?: GetBookingTrendsParams,) => {
    return [
    `/api/admin/dashboard/booking-trends`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetBookingTrendsQueryOptions = <TData = Awaited<ReturnType<typeof getBookingTrends>>, TError = string>(params?: GetBookingTrendsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingTrends>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBookingTrendsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookingTrends>>> = ({ signal }) => getBookingTrends(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBookingTrends>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBookingTrendsQueryResult = NonNullable<Awaited<ReturnType<typeof getBookingTrends>>>
export type GetBookingTrendsQueryError = string


export function useGetBookingTrends<TData = Awaited<ReturnType<typeof getBookingTrends>>, TError = string>(
 params: undefined |  GetBookingTrendsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingTrends>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookingTrends>>,
          TError,
          Awaited<ReturnType<typeof getBookingTrends>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookingTrends<TData = Awaited<ReturnType<typeof getBookingTrends>>, TError = string>(
 params?: GetBookingTrendsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingTrends>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookingTrends>>,
          TError,
          Awaited<ReturnType<typeof getBookingTrends>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookingTrends<TData = Awaited<ReturnType<typeof getBookingTrends>>, TError = string>(
 params?: GetBookingTrendsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingTrends>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get booking trends
 */

export function useGetBookingTrends<TData = Awaited<ReturnType<typeof getBookingTrends>>, TError = string>(
 params?: GetBookingTrendsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingTrends>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBookingTrendsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns conversion metrics for bookings created in the given [from,to] range. Conversion rate is defined as CONFIRMED / total bookings created in range. Defaults to the last 30 days when omitted.
 * @summary Get booking conversion rate
 */
export const getBookingConversion = (
    params?: GetBookingConversionParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BookingConversionResponse>(
      {url: `/api/admin/dashboard/booking-conversion`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetBookingConversionQueryKey = (params?: GetBookingConversionParams,) => {
    return [
    `/api/admin/dashboard/booking-conversion`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetBookingConversionQueryOptions = <TData = Awaited<ReturnType<typeof getBookingConversion>>, TError = string>(params?: GetBookingConversionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingConversion>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBookingConversionQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookingConversion>>> = ({ signal }) => getBookingConversion(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBookingConversion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBookingConversionQueryResult = NonNullable<Awaited<ReturnType<typeof getBookingConversion>>>
export type GetBookingConversionQueryError = string


export function useGetBookingConversion<TData = Awaited<ReturnType<typeof getBookingConversion>>, TError = string>(
 params: undefined |  GetBookingConversionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingConversion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookingConversion>>,
          TError,
          Awaited<ReturnType<typeof getBookingConversion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookingConversion<TData = Awaited<ReturnType<typeof getBookingConversion>>, TError = string>(
 params?: GetBookingConversionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingConversion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookingConversion>>,
          TError,
          Awaited<ReturnType<typeof getBookingConversion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookingConversion<TData = Awaited<ReturnType<typeof getBookingConversion>>, TError = string>(
 params?: GetBookingConversionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingConversion>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get booking conversion rate
 */

export function useGetBookingConversion<TData = Awaited<ReturnType<typeof getBookingConversion>>, TError = string>(
 params?: GetBookingConversionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingConversion>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBookingConversionQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




