/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateOperatorRequest,
  DeleteOperatorParams,
  GetAllOperatorsParams,
  Operator,
  PagedModelOperator
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const updateOperator = (
    id: string,
    createOperatorRequest: CreateOperatorRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Operator>(
      {url: `/api/operators/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createOperatorRequest
    },
      options);
    }
  


export const getUpdateOperatorMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOperator>>, TError,{id: string;data: CreateOperatorRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOperator>>, TError,{id: string;data: CreateOperatorRequest}, TContext> => {

const mutationKey = ['updateOperator'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOperator>>, {id: string;data: CreateOperatorRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOperator(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOperatorMutationResult = NonNullable<Awaited<ReturnType<typeof updateOperator>>>
    export type UpdateOperatorMutationBody = CreateOperatorRequest
    export type UpdateOperatorMutationError = unknown

    export const useUpdateOperator = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOperator>>, TError,{id: string;data: CreateOperatorRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOperator>>,
        TError,
        {id: string;data: CreateOperatorRequest},
        TContext
      > => {

      const mutationOptions = getUpdateOperatorMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteOperator = (
    id: string,
    params?: DeleteOperatorParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/operators/${id}`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteOperatorMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOperator>>, TError,{id: string;params?: DeleteOperatorParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOperator>>, TError,{id: string;params?: DeleteOperatorParams}, TContext> => {

const mutationKey = ['deleteOperator'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOperator>>, {id: string;params?: DeleteOperatorParams}> = (props) => {
          const {id,params} = props ?? {};

          return  deleteOperator(id,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOperatorMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOperator>>>
    
    export type DeleteOperatorMutationError = unknown

    export const useDeleteOperator = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOperator>>, TError,{id: string;params?: DeleteOperatorParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOperator>>,
        TError,
        {id: string;params?: DeleteOperatorParams},
        TContext
      > => {

      const mutationOptions = getDeleteOperatorMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllOperators = (
    params: GetAllOperatorsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PagedModelOperator>(
      {url: `/api/operators`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllOperatorsQueryKey = (params?: GetAllOperatorsParams,) => {
    return [
    `/api/operators`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllOperatorsQueryOptions = <TData = Awaited<ReturnType<typeof getAllOperators>>, TError = unknown>(params: GetAllOperatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllOperators>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllOperatorsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllOperators>>> = ({ signal }) => getAllOperators(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllOperators>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllOperatorsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllOperators>>>
export type GetAllOperatorsQueryError = unknown


export function useGetAllOperators<TData = Awaited<ReturnType<typeof getAllOperators>>, TError = unknown>(
 params: GetAllOperatorsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllOperators>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllOperators>>,
          TError,
          Awaited<ReturnType<typeof getAllOperators>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllOperators<TData = Awaited<ReturnType<typeof getAllOperators>>, TError = unknown>(
 params: GetAllOperatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllOperators>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllOperators>>,
          TError,
          Awaited<ReturnType<typeof getAllOperators>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllOperators<TData = Awaited<ReturnType<typeof getAllOperators>>, TError = unknown>(
 params: GetAllOperatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllOperators>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllOperators<TData = Awaited<ReturnType<typeof getAllOperators>>, TError = unknown>(
 params: GetAllOperatorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllOperators>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllOperatorsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createOperator = (
    createOperatorRequest: CreateOperatorRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Operator>(
      {url: `/api/operators`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOperatorRequest, signal
    },
      options);
    }
  


export const getCreateOperatorMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOperator>>, TError,{data: CreateOperatorRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createOperator>>, TError,{data: CreateOperatorRequest}, TContext> => {

const mutationKey = ['createOperator'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOperator>>, {data: CreateOperatorRequest}> = (props) => {
          const {data} = props ?? {};

          return  createOperator(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOperatorMutationResult = NonNullable<Awaited<ReturnType<typeof createOperator>>>
    export type CreateOperatorMutationBody = CreateOperatorRequest
    export type CreateOperatorMutationError = unknown

    export const useCreateOperator = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOperator>>, TError,{data: CreateOperatorRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOperator>>,
        TError,
        {data: CreateOperatorRequest},
        TContext
      > => {

      const mutationOptions = getCreateOperatorMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    