/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const handleWebhook = (
    handleWebhookBody: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/webhooks/payos`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: handleWebhookBody, signal
    },
      options);
    }
  


export const getHandleWebhookMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleWebhook>>, TError,{data: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof handleWebhook>>, TError,{data: string}, TContext> => {

const mutationKey = ['handleWebhook'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof handleWebhook>>, {data: string}> = (props) => {
          const {data} = props ?? {};

          return  handleWebhook(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type HandleWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof handleWebhook>>>
    export type HandleWebhookMutationBody = string
    export type HandleWebhookMutationError = unknown

    export const useHandleWebhook = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleWebhook>>, TError,{data: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof handleWebhook>>,
        TError,
        {data: string},
        TContext
      > => {

      const mutationOptions = getHandleWebhookMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    