/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePaymentRequest,
  PaymentResponse
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const createPayment = (
    createPaymentRequest: CreatePaymentRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaymentResponse>(
      {url: `/api/payments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPaymentRequest, signal
    },
      options);
    }
  


export const getCreatePaymentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPayment>>, TError,{data: CreatePaymentRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createPayment>>, TError,{data: CreatePaymentRequest}, TContext> => {

const mutationKey = ['createPayment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPayment>>, {data: CreatePaymentRequest}> = (props) => {
          const {data} = props ?? {};

          return  createPayment(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePaymentMutationResult = NonNullable<Awaited<ReturnType<typeof createPayment>>>
    export type CreatePaymentMutationBody = CreatePaymentRequest
    export type CreatePaymentMutationError = unknown

    export const useCreatePayment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPayment>>, TError,{data: CreatePaymentRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPayment>>,
        TError,
        {data: CreatePaymentRequest},
        TContext
      > => {

      const mutationOptions = getCreatePaymentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const verifyPayment = (
    bookingId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaymentResponse>(
      {url: `/api/payments/verify/${bookingId}`, method: 'POST', signal
    },
      options);
    }
  


export const getVerifyPaymentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyPayment>>, TError,{bookingId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyPayment>>, TError,{bookingId: string}, TContext> => {

const mutationKey = ['verifyPayment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyPayment>>, {bookingId: string}> = (props) => {
          const {bookingId} = props ?? {};

          return  verifyPayment(bookingId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyPaymentMutationResult = NonNullable<Awaited<ReturnType<typeof verifyPayment>>>
    
    export type VerifyPaymentMutationError = unknown

    export const useVerifyPayment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyPayment>>, TError,{bookingId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyPayment>>,
        TError,
        {bookingId: string},
        TContext
      > => {

      const mutationOptions = getVerifyPaymentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getPayment = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaymentResponse>(
      {url: `/api/payments/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPaymentQueryKey = (id?: string,) => {
    return [
    `/api/payments/${id}`
    ] as const;
    }

    
export const getGetPaymentQueryOptions = <TData = Awaited<ReturnType<typeof getPayment>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPayment>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPaymentQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPayment>>> = ({ signal }) => getPayment(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPayment>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPaymentQueryResult = NonNullable<Awaited<ReturnType<typeof getPayment>>>
export type GetPaymentQueryError = unknown


export function useGetPayment<TData = Awaited<ReturnType<typeof getPayment>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPayment>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPayment>>,
          TError,
          Awaited<ReturnType<typeof getPayment>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPayment<TData = Awaited<ReturnType<typeof getPayment>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPayment>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPayment>>,
          TError,
          Awaited<ReturnType<typeof getPayment>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPayment<TData = Awaited<ReturnType<typeof getPayment>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPayment>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPayment<TData = Awaited<ReturnType<typeof getPayment>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPayment>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPaymentQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPaymentByBooking = (
    bookingId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaymentResponse>(
      {url: `/api/payments/booking/${bookingId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPaymentByBookingQueryKey = (bookingId?: string,) => {
    return [
    `/api/payments/booking/${bookingId}`
    ] as const;
    }

    
export const getGetPaymentByBookingQueryOptions = <TData = Awaited<ReturnType<typeof getPaymentByBooking>>, TError = unknown>(bookingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaymentByBooking>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPaymentByBookingQueryKey(bookingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPaymentByBooking>>> = ({ signal }) => getPaymentByBooking(bookingId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(bookingId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPaymentByBooking>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPaymentByBookingQueryResult = NonNullable<Awaited<ReturnType<typeof getPaymentByBooking>>>
export type GetPaymentByBookingQueryError = unknown


export function useGetPaymentByBooking<TData = Awaited<ReturnType<typeof getPaymentByBooking>>, TError = unknown>(
 bookingId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaymentByBooking>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPaymentByBooking>>,
          TError,
          Awaited<ReturnType<typeof getPaymentByBooking>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPaymentByBooking<TData = Awaited<ReturnType<typeof getPaymentByBooking>>, TError = unknown>(
 bookingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaymentByBooking>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPaymentByBooking>>,
          TError,
          Awaited<ReturnType<typeof getPaymentByBooking>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPaymentByBooking<TData = Awaited<ReturnType<typeof getPaymentByBooking>>, TError = unknown>(
 bookingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaymentByBooking>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPaymentByBooking<TData = Awaited<ReturnType<typeof getPaymentByBooking>>, TError = unknown>(
 bookingId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPaymentByBooking>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPaymentByBookingQueryOptions(bookingId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




