/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Bus Ticket Booking API
 * REST API for searching trips, booking seats and managing bus ticket operations.
 * OpenAPI spec version: v1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BookingLookupRequest,
  BookingResponse,
  CreateBookingRequest,
  GetUserBookingsParams,
  PagedModelBookingResponse,
  UpdateBookingRequest
} from '../../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns detailed information for a single booking.
 * @summary Get booking by ID
 */
export const getBookingById = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BookingResponse>(
      {url: `/api/bookings/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetBookingByIdQueryKey = (id?: string,) => {
    return [
    `/api/bookings/${id}`
    ] as const;
    }

    
export const getGetBookingByIdQueryOptions = <TData = Awaited<ReturnType<typeof getBookingById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBookingByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookingById>>> = ({ signal }) => getBookingById(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBookingById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBookingByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getBookingById>>>
export type GetBookingByIdQueryError = unknown


export function useGetBookingById<TData = Awaited<ReturnType<typeof getBookingById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookingById>>,
          TError,
          Awaited<ReturnType<typeof getBookingById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookingById<TData = Awaited<ReturnType<typeof getBookingById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookingById>>,
          TError,
          Awaited<ReturnType<typeof getBookingById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookingById<TData = Awaited<ReturnType<typeof getBookingById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get booking by ID
 */

export function useGetBookingById<TData = Awaited<ReturnType<typeof getBookingById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBookingByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateBooking = (
    id: string,
    updateBookingRequest: UpdateBookingRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<BookingResponse>(
      {url: `/api/bookings/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateBookingRequest
    },
      options);
    }
  


export const getUpdateBookingMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBooking>>, TError,{id: string;data: UpdateBookingRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateBooking>>, TError,{id: string;data: UpdateBookingRequest}, TContext> => {

const mutationKey = ['updateBooking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBooking>>, {id: string;data: UpdateBookingRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateBooking(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateBookingMutationResult = NonNullable<Awaited<ReturnType<typeof updateBooking>>>
    export type UpdateBookingMutationBody = UpdateBookingRequest
    export type UpdateBookingMutationError = unknown

    export const useUpdateBooking = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBooking>>, TError,{id: string;data: UpdateBookingRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateBooking>>,
        TError,
        {id: string;data: UpdateBookingRequest},
        TContext
      > => {

      const mutationOptions = getUpdateBookingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Marks a booking as confirmed after successful payment.
 * @summary Confirm booking
 */
export const confirmBooking = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<BookingResponse>(
      {url: `/api/bookings/${id}/confirm`, method: 'PUT'
    },
      options);
    }
  


export const getConfirmBookingMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmBooking>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmBooking>>, TError,{id: string}, TContext> => {

const mutationKey = ['confirmBooking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmBooking>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  confirmBooking(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmBookingMutationResult = NonNullable<Awaited<ReturnType<typeof confirmBooking>>>
    
    export type ConfirmBookingMutationError = unknown

    /**
 * @summary Confirm booking
 */
export const useConfirmBooking = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmBooking>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmBooking>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getConfirmBookingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Cancels an existing booking and releases seats.
 * @summary Cancel booking
 */
export const cancelBooking = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<BookingResponse>(
      {url: `/api/bookings/${id}/cancel`, method: 'PUT'
    },
      options);
    }
  


export const getCancelBookingMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelBooking>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelBooking>>, TError,{id: string}, TContext> => {

const mutationKey = ['cancelBooking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelBooking>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  cancelBooking(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CancelBookingMutationResult = NonNullable<Awaited<ReturnType<typeof cancelBooking>>>
    
    export type CancelBookingMutationError = unknown

    /**
 * @summary Cancel booking
 */
export const useCancelBooking = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelBooking>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelBooking>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getCancelBookingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a new booking for a given trip and passenger details.
 * @summary Create booking
 */
export const createBooking = (
    createBookingRequest: CreateBookingRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BookingResponse>(
      {url: `/api/bookings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createBookingRequest, signal
    },
      options);
    }
  


export const getCreateBookingMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBooking>>, TError,{data: CreateBookingRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createBooking>>, TError,{data: CreateBookingRequest}, TContext> => {

const mutationKey = ['createBooking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBooking>>, {data: CreateBookingRequest}> = (props) => {
          const {data} = props ?? {};

          return  createBooking(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateBookingMutationResult = NonNullable<Awaited<ReturnType<typeof createBooking>>>
    export type CreateBookingMutationBody = CreateBookingRequest
    export type CreateBookingMutationError = unknown

    /**
 * @summary Create booking
 */
export const useCreateBooking = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBooking>>, TError,{data: CreateBookingRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBooking>>,
        TError,
        {data: CreateBookingRequest},
        TContext
      > => {

      const mutationOptions = getCreateBookingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns booking details given booking code and passenger email.
 * @summary Lookup booking by code and email
 */
export const lookupBooking = (
    bookingLookupRequest: BookingLookupRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BookingResponse>(
      {url: `/api/bookings/lookup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bookingLookupRequest, signal
    },
      options);
    }
  


export const getLookupBookingMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lookupBooking>>, TError,{data: BookingLookupRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof lookupBooking>>, TError,{data: BookingLookupRequest}, TContext> => {

const mutationKey = ['lookupBooking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lookupBooking>>, {data: BookingLookupRequest}> = (props) => {
          const {data} = props ?? {};

          return  lookupBooking(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LookupBookingMutationResult = NonNullable<Awaited<ReturnType<typeof lookupBooking>>>
    export type LookupBookingMutationBody = BookingLookupRequest
    export type LookupBookingMutationError = unknown

    /**
 * @summary Lookup booking by code and email
 */
export const useLookupBooking = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lookupBooking>>, TError,{data: BookingLookupRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lookupBooking>>,
        TError,
        {data: BookingLookupRequest},
        TContext
      > => {

      const mutationOptions = getLookupBookingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns a paginated list of bookings for the authenticated user.
 * @summary Get current user bookings
 */
export const getUserBookings = (
    params: GetUserBookingsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PagedModelBookingResponse>(
      {url: `/api/bookings/user`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetUserBookingsQueryKey = (params?: GetUserBookingsParams,) => {
    return [
    `/api/bookings/user`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetUserBookingsQueryOptions = <TData = Awaited<ReturnType<typeof getUserBookings>>, TError = unknown>(params: GetUserBookingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBookings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserBookingsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserBookings>>> = ({ signal }) => getUserBookings(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserBookings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserBookingsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserBookings>>>
export type GetUserBookingsQueryError = unknown


export function useGetUserBookings<TData = Awaited<ReturnType<typeof getUserBookings>>, TError = unknown>(
 params: GetUserBookingsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBookings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserBookings>>,
          TError,
          Awaited<ReturnType<typeof getUserBookings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserBookings<TData = Awaited<ReturnType<typeof getUserBookings>>, TError = unknown>(
 params: GetUserBookingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBookings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserBookings>>,
          TError,
          Awaited<ReturnType<typeof getUserBookings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserBookings<TData = Awaited<ReturnType<typeof getUserBookings>>, TError = unknown>(
 params: GetUserBookingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBookings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user bookings
 */

export function useGetUserBookings<TData = Awaited<ReturnType<typeof getUserBookings>>, TError = unknown>(
 params: GetUserBookingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBookings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserBookingsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns list of seat codes that are booked for a given trip.
 * @summary Get booked seats for trip
 */
export const getBookedSeatsForTrip = (
    tripId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<string[]>(
      {url: `/api/bookings/trip/${tripId}/seats`, method: 'GET', signal
    },
      options);
    }
  



export const getGetBookedSeatsForTripQueryKey = (tripId?: string,) => {
    return [
    `/api/bookings/trip/${tripId}/seats`
    ] as const;
    }

    
export const getGetBookedSeatsForTripQueryOptions = <TData = Awaited<ReturnType<typeof getBookedSeatsForTrip>>, TError = unknown>(tripId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookedSeatsForTrip>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBookedSeatsForTripQueryKey(tripId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookedSeatsForTrip>>> = ({ signal }) => getBookedSeatsForTrip(tripId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(tripId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBookedSeatsForTrip>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBookedSeatsForTripQueryResult = NonNullable<Awaited<ReturnType<typeof getBookedSeatsForTrip>>>
export type GetBookedSeatsForTripQueryError = unknown


export function useGetBookedSeatsForTrip<TData = Awaited<ReturnType<typeof getBookedSeatsForTrip>>, TError = unknown>(
 tripId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookedSeatsForTrip>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookedSeatsForTrip>>,
          TError,
          Awaited<ReturnType<typeof getBookedSeatsForTrip>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookedSeatsForTrip<TData = Awaited<ReturnType<typeof getBookedSeatsForTrip>>, TError = unknown>(
 tripId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookedSeatsForTrip>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookedSeatsForTrip>>,
          TError,
          Awaited<ReturnType<typeof getBookedSeatsForTrip>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookedSeatsForTrip<TData = Awaited<ReturnType<typeof getBookedSeatsForTrip>>, TError = unknown>(
 tripId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookedSeatsForTrip>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get booked seats for trip
 */

export function useGetBookedSeatsForTrip<TData = Awaited<ReturnType<typeof getBookedSeatsForTrip>>, TError = unknown>(
 tripId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookedSeatsForTrip>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBookedSeatsForTripQueryOptions(tripId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




